import { useState } from "react";
import { X, ZoomIn } from "lucide-react";

interface GalleryItem {
  id: string;
  title: string;
  theme: string;
  size: string;
}

const galleryItems: GalleryItem[] = [
  { id: "1", title: "Lost Catacombs", theme: "Dungeon", size: "100×100" },
  { id: "2", title: "Dragon's Lair", theme: "Cave", size: "150×150" },
  { id: "3", title: "Royal Castle", theme: "Castle", size: "120×120" },
  { id: "4", title: "Whisper Woods", theme: "Forest", size: "100×100" },
  { id: "5", title: "Ancient Tomb", theme: "Dungeon", size: "80×80" },
  { id: "6", title: "Crystal Caverns", theme: "Cave", size: "120×120" },
];

export default function Gallery() {
  const [selectedId, setSelectedId] = useState<string | null>(null);

  return (
    <section className="py-20 px-4">
      <div className="max-w-6xl mx-auto">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-serif font-bold mb-4">
            <span className="text-gradient">Gallery</span>
          </h2>
          <p className="text-foreground/70 text-lg max-w-2xl mx-auto">
            Explore maps generated by our community. Click any map to view in
            detail.
          </p>
        </div>

        {/* Gallery Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
          {galleryItems.map((item) => (
            <div
              key={item.id}
              onClick={() => setSelectedId(item.id)}
              className="group cursor-pointer"
            >
              <div className="card-dark rounded-xl overflow-hidden transition-all duration-300 hover:shadow-xl hover:shadow-gold-500/20 hover:border-gold-500/50 hover:-translate-y-1">
                {/* Thumbnail Image */}
                <div className="relative aspect-square bg-gradient-to-br from-stone-800 to-stone-700 overflow-hidden">
                  {/* SVG Grid Pattern */}
                  <svg
                    viewBox="0 0 100 100"
                    className="w-full h-full opacity-30"
                  >
                    <defs>
                      <pattern
                        id={`grid-${item.id}`}
                        width="10"
                        height="10"
                        patternUnits="userSpaceOnUse"
                      >
                        <path
                          d="M 10 0 L 0 0 0 10"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="0.5"
                          className="text-gold-600"
                        />
                      </pattern>
                    </defs>
                    <rect
                      width="100"
                      height="100"
                      fill={`url(#grid-${item.id})`}
                    />
                  </svg>

                  {/* Pseudo rooms/chambers */}
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="grid grid-cols-2 gap-4 w-3/4 h-3/4">
                      {[...Array(4)].map((_, i) => (
                        <div
                          key={i}
                          className="bg-stone-600/30 border border-gold-600/50 rounded"
                        />
                      ))}
                    </div>
                  </div>

                  {/* Overlay */}
                  <div className="absolute inset-0 bg-gradient-to-t from-stone-900 via-transparent to-transparent opacity-60 group-hover:opacity-40 transition-opacity" />

                  {/* Zoom Icon */}
                  <div className="absolute inset-0 flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                    <div className="bg-stone-900/80 rounded-full p-4 backdrop-blur">
                      <ZoomIn className="h-8 w-8 text-gold-400" />
                    </div>
                  </div>
                </div>

                {/* Card Content */}
                <div className="p-6">
                  <h3 className="text-lg font-serif font-bold text-foreground mb-2 group-hover:text-gold-400 transition-colors">
                    {item.title}
                  </h3>
                  <div className="flex justify-between text-sm text-foreground/60">
                    <span className="bg-gold-900/30 px-3 py-1 rounded text-gold-300">
                      {item.theme}
                    </span>
                    <span>{item.size}</span>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Modal */}
        {selectedId && (
          <div
            className="fixed inset-0 bg-black/80 backdrop-blur z-50 flex items-center justify-center p-4"
            onClick={() => setSelectedId(null)}
          >
            <div
              className="bg-card rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-hidden"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Modal Header */}
              <div className="flex items-center justify-between p-6 border-b border-gold-900/30">
                <div>
                  <h3 className="text-2xl font-serif font-bold text-foreground">
                    {galleryItems.find((i) => i.id === selectedId)?.title}
                  </h3>
                  <p className="text-foreground/60 text-sm mt-1">
                    Theme:{" "}
                    {galleryItems.find((i) => i.id === selectedId)?.theme} |
                    Size:{" "}
                    {galleryItems.find((i) => i.id === selectedId)?.size}
                  </p>
                </div>
                <button
                  onClick={() => setSelectedId(null)}
                  className="text-foreground/60 hover:text-gold-400 transition-colors"
                >
                  <X className="h-6 w-6" />
                </button>
              </div>

              {/* Modal Content */}
              <div className="p-6">
                <div className="aspect-square bg-gradient-to-br from-stone-800 to-stone-700 rounded-lg overflow-hidden flex items-center justify-center">
                  <svg
                    viewBox="0 0 100 100"
                    className="w-full h-full opacity-20"
                  >
                    <defs>
                      <pattern
                        id="grid-modal"
                        width="5"
                        height="5"
                        patternUnits="userSpaceOnUse"
                      >
                        <path
                          d="M 5 0 L 0 0 0 5"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="0.3"
                          className="text-gold-600"
                        />
                      </pattern>
                    </defs>
                    <rect width="100" height="100" fill="url(#grid-modal)" />
                  </svg>
                </div>

                {/* Action Buttons */}
                <div className="grid grid-cols-2 gap-4 mt-6">
                  <button className="px-6 py-2 border border-gold-900/40 rounded-lg text-foreground hover:border-gold-500 hover:bg-gold-900/10 transition-all">
                    Download
                  </button>
                  <button className="px-6 py-2 bg-gradient-to-r from-gold-600 to-gold-700 text-stone-900 rounded-lg font-semibold hover:shadow-lg hover:shadow-gold-500/40 transition-all">
                    Use as Template
                  </button>
                </div>
              </div>
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
